-- Parfum de grande marque dont s'inspire chaque fragrance (liste de prix Tribe, septembre 2026).
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "inspiredBy" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "inspiredBrand" TEXT;

UPDATE "Product" AS p
SET "inspiredBy" = v.name, "inspiredBrand" = v.brand, "updatedAt" = now()
FROM (VALUES
('chogan-1224', 'Black Opium', 'Yves Saint Laurent'),
('chogan-1227', 'La Nuit de l''Homme', 'Yves Saint Laurent'),
('chogan-1245', 'Coco Mademoiselle', 'Chanel'),
('chogan-1274', 'J''adore', 'Dior'),
('chogan-1279', 'Le Mâle', 'Jean Paul Gaultier'),
('chogan-1301', 'Alien', 'Thierry Mugler'),
('chogan-1302', 'Black Code', 'Armani'),
('chogan-1307', 'J''adore', 'Dior'),
('chogan-1318', 'Lady Million', 'Paco Rabanne'),
('chogan-1326', 'Alien', 'Thierry Mugler'),
('chogan-1343', 'Coco Mademoiselle', 'Chanel'),
('chogan-1356', 'Hypnotic Poison', 'Dior'),
('chogan-1357', 'La Vie est Belle', 'Lancôme'),
('chogan-1360', 'La Vie est Belle', 'Lancôme'),
('chogan-1362', 'Black Opium', 'Yves Saint Laurent'),
('chogan-1369', 'Fahrenheit', 'Dior'),
('chogan-1375', 'One Million', 'Paco Rabanne'),
('chogan-1376', 'Acqua di Giò', 'Armani'),
('chogan-1377', 'Hugo', 'Hugo Boss'),
('chogan-1401', 'Lady Million', 'Paco Rabanne'),
('chogan-1402', 'Hypnotic Poison', 'Dior'),
('chogan-1452', 'Invictus', 'Paco Rabanne'),
('chogan-1781', 'Aventus', 'Creed'),
('chogan-1792', 'X for Men', 'Clive Christian'),
('chogan-6486', 'Scandal', 'Jean Paul Gaultier'),
('chogan-6488', 'L''Interdit', 'Givenchy'),
('chogan-6506', 'Scandal', 'Jean Paul Gaultier'),
('chogan-6508', 'L''Interdit', 'Givenchy'),
('chogan-6510', 'Sì', 'Armani'),
('chogan-6512', 'Sauvage', 'Dior'),
('chogan-6513', 'Intense Café', 'Montale'),
('chogan-6514', 'Sì', 'Armani'),
('chogan-7974', 'Baccarat Rouge 540', 'Maison Francis Kurkdjian'),
('chogan-7975', 'Lost Cherry', 'Tom Ford'),
('chogan-7976', 'Erba Pura', 'Xerjoff'),
('chogan-7977', 'Megamare', 'Orto Parisi'),
('chogan-7978', 'Bitter Peach', 'Tom Ford'),
('chogan-8888', 'Ombré Leather', 'Tom Ford'),
('chogan-8892', 'Green Irish Tweed', 'Creed'),
('chogan-9017', 'Aventus for Her', 'Creed'),
('chogan-9033', 'Blv', 'Bulgari'),
('chogan-9037', 'Man', 'Bulgari'),
('chogan-9041', 'Silver Mountain Water', 'Creed'),
('chogan-9049', 'Millésime Impérial', 'Creed'),
('chogan-9055', 'Scent Intense', 'Costume National'),
('chogan-9065', 'Himalaya', 'Creed'),
('chogan-9069', 'Ultraviolet', 'Paco Rabanne'),
('chogan-9073', 'Signorina', 'Ferragamo'),
('chogan-9081', 'Man in Black', 'Bulgari'),
('chogan-9087', 'Amo Ferragamo', 'Ferragamo'),
('chogan-9091', 'White Aoud', 'Montale'),
('chogan-10948', 'Burberry Woman', 'Burberry'),
('chogan-10953', 'Burberry for Men', 'Burberry'),
('chogan-10978', 'CK One', 'Calvin Klein'),
('chogan-10993', 'Chloé', 'Chloé'),
('chogan-11008', 'Love, Chloé', 'Chloé'),
('chogan-11023', 'Flora', 'Gucci'),
('chogan-11038', 'Guilty', 'Gucci'),
('chogan-11053', 'Guilty', 'Gucci'),
('chogan-11068', 'Hugo Woman', 'Hugo Boss'),
('chogan-11083', 'Hugo', 'Hugo Boss'),
('chogan-11098', 'The Scent', 'Hugo Boss'),
('chogan-11278', 'Boss Bottled Absolu', 'Hugo Boss'),
('chogan-11293', 'Goddess', 'Burberry'),
('chogan-11466', 'Born in Roma Intense', 'Valentino'),
('chogan-11481', 'Born in Roma Donna', 'Valentino'),
('chogan-11696', 'One Million', 'Paco Rabanne'),
('chogan-11711', 'Acqua di Giò', 'Armani'),
('chogan-11726', 'Fahrenheit', 'Dior'),
('chogan-11741', 'The One', 'Dolce & Gabbana'),
('chogan-11751', 'Opium', 'Yves Saint Laurent'),
('chogan-11766', 'J''adore', 'Dior'),
('chogan-11786', 'Alien', 'Thierry Mugler'),
('chogan-11791', 'Light Blue', 'Dolce & Gabbana'),
('chogan-11816', 'Manifesto', 'Yves Saint Laurent'),
('chogan-11821', 'Eau Sauvage', 'Dior'),
('chogan-11841', 'Roma', 'Laura Biagiotti'),
('chogan-11851', 'Le Mâle', 'Jean Paul Gaultier'),
('chogan-11861', 'Déclaration', 'Cartier'),
('chogan-11886', 'Lady Million', 'Paco Rabanne'),
('chogan-11906', 'La Nuit de l''Homme', 'Yves Saint Laurent'),
('chogan-11921', 'Light Blue', 'Dolce & Gabbana'),
('chogan-11926', 'Terre d''Hermès', 'Hermès'),
('chogan-11941', 'Hypnotic Poison', 'Dior'),
('chogan-11966', 'For Her', 'Narciso Rodriguez'),
('chogan-11981', 'N°5', 'Chanel'),
('chogan-12001', 'Flower', 'Kenzo'),
('chogan-12016', 'Trésor in Love', 'Lancôme'),
('chogan-12031', 'Angel', 'Thierry Mugler'),
('chogan-12046', 'L''Eau d''Issey', 'Issey Miyake'),
('chogan-12061', 'Black XS', 'Paco Rabanne'),
('chogan-12076', 'Spicebomb', 'Viktor & Rolf'),
('chogan-12091', 'Black Code', 'Armani'),
('chogan-12121', 'Bleu de Chanel', 'Chanel'),
('chogan-12136', 'Miss Dior Chérie', 'Dior'),
('chogan-12151', 'Hypnôse', 'Lancôme'),
('chogan-12166', 'La Vie est Belle', 'Lancôme'),
('chogan-12196', 'Crystal Noir', 'Versace'),
('chogan-12206', 'Allure Homme', 'Chanel'),
('chogan-12226', 'Dolce', 'Dolce & Gabbana'),
('chogan-12241', 'Coco Mademoiselle', 'Chanel'),
('chogan-12256', 'Pasha', 'Cartier'),
('chogan-12271', 'Narciso', 'Narciso Rodriguez'),
('chogan-12286', 'Black Orchid', 'Tom Ford'),
('chogan-12301', 'Black Opium', 'Yves Saint Laurent'),
('chogan-12316', 'Ange ou Démon', 'Givenchy'),
('chogan-12321', 'Omnia Amethyste', 'Bulgari'),
('chogan-12346', 'Invictus', 'Paco Rabanne'),
('chogan-12361', 'Intenso', 'Dolce & Gabbana'),
('chogan-12376', 'Omnia Indian Garnet', 'Bulgari'),
('chogan-12391', 'Olympéa', 'Paco Rabanne'),
('chogan-12421', 'Acqua di Sale', 'Profumum Roma'),
('chogan-12436', 'The One', 'Dolce & Gabbana'),
('chogan-12451', 'Allure', 'Chanel'),
('chogan-12466', 'Patchouli', 'Réminiscence'),
('chogan-12496', 'Acqua di Gioia', 'Armani'),
('chogan-12506', 'MYSLF', 'Yves Saint Laurent'),
('chogan-12526', 'Sì', 'Armani'),
('chogan-12541', 'Classique Essence', 'Jean Paul Gaultier'),
('chogan-12566', 'Dylan Blue', 'Versace'),
('chogan-12586', 'Chance', 'Chanel'),
('chogan-12601', 'Legend', 'Montblanc'),
('chogan-12616', 'Wanted', 'Azzaro'),
('chogan-12631', 'Mon Paris', 'Yves Saint Laurent'),
('chogan-12661', 'Poison Girl', 'Dior'),
('chogan-12671', 'Chrome', 'Azzaro'),
('chogan-12706', 'Sauvage', 'Dior'),
('chogan-12721', 'Gabrielle', 'Chanel'),
('chogan-12751', 'Joy', 'Dior'),
('chogan-12766', 'Mandarino di Amalfi', 'Tom Ford'),
('chogan-12781', 'Idôle', 'Lancôme'),
('chogan-12796', 'Yes I Am', 'Cacharel'),
('chogan-12811', 'Scandal', 'Jean Paul Gaultier'),
('chogan-12826', 'La Petite Robe Noire', 'Guerlain'),
('chogan-12841', 'L''Interdit', 'Givenchy'),
('chogan-12856', 'Libre', 'Yves Saint Laurent'),
('chogan-12871', 'Paradoxe', 'Prada'),
('chogan-12886', 'Good Girl', 'Carolina Herrera'),
('chogan-12896', 'My Way', 'Giorgio Armani'),
('chogan-12916', 'Dior Homme Intense', 'Dior'),
('chogan-12931', 'Eros', 'Versace'),
('chogan-12946', 'Black Afgano', 'Nasomatto'),
('chogan-12981', 'Velvet Amber Skin', 'Dolce & Gabbana'),
('chogan-12991', 'Velvet Amber Sun', 'Dolce & Gabbana'),
('chogan-13001', 'Lost Cherry', 'Tom Ford'),
('chogan-13011', 'Neroli Portofino', 'Tom Ford'),
('chogan-13021', 'Intense Café', 'Montale'),
('chogan-13036', 'Sur la Route', 'Louis Vuitton'),
('chogan-13046', 'Ombre Nomade', 'Louis Vuitton'),
('chogan-13066', 'Tobacco Vanille', 'Tom Ford'),
('chogan-13076', 'Baccarat Rouge 540', 'Maison Francis Kurkdjian'),
('chogan-13086', 'Zeta', 'Morph'),
('chogan-13091', 'Sole di Positano', 'Tom Ford'),
('chogan-13106', 'Oud Wood', 'Tom Ford'),
('chogan-13111', 'Megamare', 'Orto Parisi'),
('chogan-13121', 'Vanille Fatale', 'Tom Ford'),
('chogan-13136', 'Bitter Peach', 'Tom Ford'),
('chogan-13141', 'Naxos', 'Xerjoff'),
('chogan-13146', 'Good Girl Gone Bad', 'Kilian'),
('chogan-13161', 'Wood Whisper', 'Ojar'),
('chogan-13176', 'Vanilla Powder', 'Matière Première'),
('chogan-13181', 'Bianco Latte', 'Giardini di Toscana'),
('chogan-13196', 'The Spirit of Dubai', 'Turath'),
('chogan-13221', 'Bois d''Argent', 'Dior'),
('chogan-13266', 'Rouge', 'Balmain'),
('chogan-13276', 'Les Sables Roses', 'Louis Vuitton'),
('chogan-13286', 'Soleil Blanc', 'Tom Ford'),
('chogan-13296', 'Kirkè', 'Tiziana Terenzi'),
('chogan-13321', 'J''adore L''Or', 'Dior'),
('chogan-13331', 'Erba Pura', 'Xerjoff'),
('chogan-13341', 'Devotion', 'Dolce & Gabbana'),
('chogan-13686', 'Miutine', 'Miu Miu'),
('chogan-13706', 'Paradigme', 'Prada'),
('chogan-16116', 'Aventus', 'Creed')
) AS v(id, name, brand)
WHERE p."id" = v.id
  AND (p."inspiredBy" IS DISTINCT FROM v.name OR p."inspiredBrand" IS DISTINCT FROM v.brand);
